// JLPT 단어 데이터베이스
const jlptWords = {
  N5: [
    { word: '食べる', kanji: '[食べる]', reading: 'たべる · taberu', pos: '동사', meanings: ['먹다'] },
    { word: '飲む', kanji: '[飲む]', reading: 'のむ · nomu', pos: '동사', meanings: ['마시다'] },
    { word: '見る', kanji: '[見る]', reading: 'みる · miru', pos: '동사', meanings: ['보다'] },
    { word: '聞く', kanji: '[聞く]', reading: 'きく · kiku', pos: '동사', meanings: ['듣다', '묻다'] },
    { word: '話す', kanji: '[話す]', reading: 'はなす · hanasu', pos: '동사', meanings: ['말하다', '이야기하다'] },
    { word: '書く', kanji: '[書く]', reading: 'かく · kaku', pos: '동사', meanings: ['쓰다'] },
    { word: '読む', kanji: '[読む]', reading: 'よむ · yomu', pos: '동사', meanings: ['읽다'] },
    { word: '行く', kanji: '[行く]', reading: 'いく · iku', pos: '동사', meanings: ['가다'] },
    { word: '来る', kanji: '[来る]', reading: 'くる · kuru', pos: '동사', meanings: ['오다'] },
    { word: '帰る', kanji: '[帰る]', reading: 'かえる · kaeru', pos: '동사', meanings: ['돌아가다', '귀가하다'] },
    { word: '大きい', kanji: '[大きい]', reading: 'おおきい · ōkii', pos: '형용사', meanings: ['크다'] },
    { word: '小さい', kanji: '[小さい]', reading: 'ちいさい · chiisai', pos: '형용사', meanings: ['작다'] },
    { word: '新しい', kanji: '[新しい]', reading: 'あたらしい · atarashii', pos: '형용사', meanings: ['새롭다', '새것이다'] },
    { word: '古い', kanji: '[古い]', reading: 'ふるい · furui', pos: '형용사', meanings: ['오래되다', '낡다'] },
    { word: '高い', kanji: '[高い]', reading: 'たかい · takai', pos: '형용사', meanings: ['높다', '비싸다'] },
    { word: '安い', kanji: '[安い]', reading: 'やすい · yasui', pos: '형용사', meanings: ['싸다', '저렴하다'] },
    { word: '学校', kanji: '[学校]', reading: 'がっこう · gakko', pos: '명사', meanings: ['학교'] },
    { word: '先生', kanji: '[先生]', reading: 'せんせい · sensei', pos: '명사', meanings: ['선생님', '의사'] },
    { word: '学生', kanji: '[学生]', reading: 'がくせい · gakusei', pos: '명사', meanings: ['학생'] },
    { word: '友達', kanji: '[友達]', reading: 'ともだち · tomodachi', pos: '명사', meanings: ['친구'] },
    { word: '家族', kanji: '[家族]', reading: 'かぞく · kazoku', pos: '명사', meanings: ['가족'] },
    { word: '時間', kanji: '[時間]', reading: 'じかん · jikan', pos: '명사', meanings: ['시간'] },
    { word: '今日', kanji: '[今日]', reading: 'きょう · kyō', pos: '명사', meanings: ['오늘'] },
    { word: '明日', kanji: '[明日]', reading: 'あした · ashita', pos: '명사', meanings: ['내일'] },
    { word: '昨日', kanji: '[昨日]', reading: 'きのう · kinō', pos: '명사', meanings: ['어제'] },
  ],
  N4: [
    { word: '運動', kanji: '[運動]', reading: 'うんどう · undō', pos: '명사', meanings: ['운동'] },
    { word: '練習', kanji: '[練習]', reading: 'れんしゅう · renshū', pos: '명사', meanings: ['연습'] },
    { word: '説明', kanji: '[説明]', reading: 'せつめい · setsumei', pos: '명사', meanings: ['설명'] },
    { word: '準備', kanji: '[準備]', reading: 'じゅんび · junbi', pos: '명사', meanings: ['준비'] },
    { word: '約束', kanji: '[約束]', reading: 'やくそく · yakusoku', pos: '명사', meanings: ['약속'] },
    { word: '経験', kanji: '[経験]', reading: 'けいけん · keiken', pos: '명사', meanings: ['경험'] },
    { word: '生活', kanji: '[生活]', reading: 'せいかつ · seikatsu', pos: '명사', meanings: ['생활'] },
    { word: '社会', kanji: '[社会]', reading: 'しゃかい · shakai', pos: '명사', meanings: ['사회'] },
    { word: '変える', kanji: '[変える]', reading: 'かえる · kaeru', pos: '동사', meanings: ['바꾸다', '변경하다'] },
    { word: '決める', kanji: '[決める]', reading: 'きめる · kimeru', pos: '동사', meanings: ['결정하다'] },
    { word: '続ける', kanji: '[続ける]', reading: 'つづける · tsuzukeru', pos: '동사', meanings: ['계속하다'] },
    { word: '集める', kanji: '[集める]', reading: 'あつめる · atsumeru', pos: '동사', meanings: ['모으다'] },
    { word: '心配', kanji: '[心配]', reading: 'しんぱい · shinpai', pos: '명사', meanings: ['걱정', '염려'] },
    { word: '丁寧', kanji: '[丁寧]', reading: 'ていねい · teinei', pos: '형용사', meanings: ['정중하다', '꼼꼼하다'] },
    { word: '親切', kanji: '[親切]', reading: 'しんせつ · shinsetsu', pos: '형용사', meanings: ['친절하다'] },
  ],
  N3: [
    { word: '影響', kanji: '[影響]', reading: 'えいきょう · eikyō', pos: '명사', meanings: ['영향'] },
    { word: '原因', kanji: '[原因]', reading: 'げんいん · gen\'in', pos: '명사', meanings: ['원인'] },
    { word: '結果', kanji: '[結果]', reading: 'けっか · kekka', pos: '명사', meanings: ['결과'] },
    { word: '可能', kanji: '[可能]', reading: 'かのう · kanō', pos: '형용사', meanings: ['가능하다'] },
    { word: '必要', kajna: '[必要]', reading: 'ひつよう · hitsuyō', pos: '형용사', meanings: ['필요하다'] },
    { word: '危険', kanji: '[危険]', reading: 'きけん · kiken', pos: '형용사', meanings: ['위험하다'] },
    { word: '正確', kanji: '[正確]', reading: 'せいかく · seikaku', pos: '형용사', meanings: ['정확하다'] },
    { word: '複雑', kanji: '[複雑]', reading: 'ふくざつ · fukuzatsu', pos: '형용사', meanings: ['복잡하다'] },
    { word: '認める', kanji: '[認める]', reading: 'みとめる · mitomeru', pos: '동사', meanings: ['인정하다', '허가하다'] },
    { word: '断る', kanji: '[断る]', reading: 'ことわる · kotowaru', pos: '동사', meanings: ['거절하다'] },
    { word: '相談', kanji: '[相談]', reading: 'そうだん · sōdan', pos: '명사', meanings: ['상담', '의논'] },
    { word: '目的', kanji: '[目的]', reading: 'もくてき · mokuteki', pos: '명사', meanings: ['목적'] },
    { word: '方法', kanji: '[方法]', reading: 'ほうほう · hōhō', pos: '명사', meanings: ['방법'] },
    { word: '美しい', kanji: '[美しい]', reading: 'うつくしい · utsukushii', pos: '형용사', meanings: ['아름답다', '예쁘다'] },
    { word: '懐かしい', kanji: '[懐かしい]', reading: 'なつかしい · natsukashii', pos: '형용사', meanings: ['그립다', '옛날 생각이 나다'] },
  ],
  N2: [
    { word: '維持', kanji: '[維持]', reading: 'いじ · iji', pos: '명사', meanings: ['유지'] },
    { word: '促進', kanji: '[促進]', reading: 'そくしん · sokushin', pos: '명사', meanings: ['촉진'] },
    { word: '抑制', kanji: '[抑制]', reading: 'よくせい · yokusei', pos: '명사', meanings: ['억제'] },
    { word: '拡大', kanji: '[拡大]', reading: 'かくだい · kakudai', pos: '명사', meanings: ['확대'] },
    { word: '縮小', kanji: '[縮小]', reading: 'しゅくしょう · shukushō', pos: '명사', meanings: ['축소'] },
    { word: '誤解', kanji: '[誤解]', reading: 'ごかい · gokai', pos: '명사', meanings: ['오해'] },
    { word: '矛盾', kanji: '[矛盾]', reading: 'むじゅん · mujun', pos: '명사', meanings: ['모순'] },
    { word: '儚い', kanji: '[儚い]', reading: 'はかない · hakanai', pos: '형용사', meanings: ['덧없다', '무상하다'] },
    { word: '切ない', kanji: '[切ない]', reading: 'せつない · setsunai', pos: '형용사', meanings: ['가슴 아프다', '애틋하다'] },
    { word: '妥当', kanji: '[妥当]', reading: 'だとう · datō', pos: '형용사', meanings: ['타당하다', '적절하다'] },
    { word: '徐々に', kanji: '[徐々に]', reading: 'じょじょに · jojo-ni', pos: '부사', meanings: ['서서히', '점점'] },
    { word: '敢えて', kanji: '[敢えて]', reading: 'あえて · aete', pos: '부사', meanings: ['감히', '굳이'] },
  ],
  N1: [
    { word: '憂鬱', kanji: '[憂鬱]', reading: 'ゆううつ · yūutsu', pos: '명사', meanings: ['우울', '울적함'] },
    { word: '葛藤', kanji: '[葛藤]', reading: 'かっとう · kattō', pos: '명사', meanings: ['갈등', '충돌'] },
    { word: '逡巡', kanji: '[逡巡]', reading: 'しゅんじゅん · shunjun', pos: '명사', meanings: ['주저', '망설임'] },
    { word: '凛とした', kanji: '[凛とした]', reading: 'りんとした · rin-to shita', pos: '형용사', meanings: ['늠름하다', '단호하다'] },
    { word: '儚げ', kanji: '[儚げ]', reading: 'はかなげ · hakanage', pos: '형용사', meanings: ['덧없어 보이다', '허무하게 보이다'] },
    { word: '鑑みる', kanji: '[鑑みる]', reading: 'かんがみる · kangamiru', pos: '동사', meanings: ['감안하다', '비추어 보다'] },
    { word: '醸し出す', kanji: '[醸し出す]', reading: 'かもしだす · kamoshidasu', pos: '동사', meanings: ['자아내다', '풍기다'] },
    { word: '赴く', kanji: '[赴く]', reading: 'おもむく · omumuku', pos: '동사', meanings: ['향하다', '나아가다'] },
    { word: '漠然と', kanji: '[漠然と]', reading: 'ばくぜんと · bakuzen-to', pos: '부사', meanings: ['막연히', '어렴풋이'] },
    { word: '紛れもなく', kanji: '[紛れもなく]', reading: 'まぎれもなく · magirenaku', pos: '부사', meanings: ['틀림없이', '분명히'] },
  ],
};
