// JLPT 단어 데이터베이스
const jlptWords = {
  N5: [
    { word: '食べる', kanji: '[食べる]', reading: 'たべる · taberu', pos: '동사', meanings: ['먹다'] },
    { word: '飲む', kanji: '[飲む]', reading: 'のむ · nomu', pos: '동사', meanings: ['마시다'] },
    { word: '見る', kanji: '[見る]', reading: 'みる · miru', pos: '동사', meanings: ['보다'] },
    { word: '聞く', kanji: '[聞く]', reading: 'きく · kiku', pos: '동사', meanings: ['듣다', '묻다'] },
    { word: '話す', kanji: '[話す]', reading: 'はなす · hanasu', pos: '동사', meanings: ['말하다', '이야기하다'] },
    { word: '書く', kanji: '[書く]', reading: 'かく · kaku', pos: '동사', meanings: ['쓰다'] },
    { word: '読む', kanji: '[読む]', reading: 'よむ · yomu', pos: '동사', meanings: ['읽다'] },
    { word: '行く', kanji: '[行く]', reading: 'いく · iku', pos: '동사', meanings: ['가다'] },
    { word: '来る', kanji: '[来る]', reading: 'くる · kuru', pos: '동사', meanings: ['오다'] },
    { word: '帰る', kanji: '[帰る]', reading: 'かえる · kaeru', pos: '동사', meanings: ['돌아가다', '귀가하다'] },
    { word: '大きい', kanji: '[大きい]', reading: 'おおきい · ōkii', pos: '형용사', meanings: ['크다'] },
    { word: '小さい', kanji: '[小さい]', reading: 'ちいさい · chiisai', pos: '형용사', meanings: ['작다'] },
    { word: '新しい', kanji: '[新しい]', reading: 'あたらしい · atarashii', pos: '형용사', meanings: ['새롭다', '새것이다'] },
    { word: '古い', kanji: '[古い]', reading: 'ふるい · furui', pos: '형용사', meanings: ['오래되다', '낡다'] },
    { word: '高い', kanji: '[高い]', reading: 'たかい · takai', pos: '형용사', meanings: ['높다', '비싸다'] },
    { word: '安い', kanji: '[安い]', reading: 'やすい · yasui', pos: '형용사', meanings: ['싸다', '저렴하다'] },
    { word: '學校', kanji: '[学校]', reading: 'がっこう · gakko', pos: '명사', meanings: ['학교'] },
    { word: '先生', kanji: '[先生]', reading: 'せんせい · sensei', pos: '명사', meanings: ['선생님', '의사'] },
    { word: '学生', kanji: '[学生]', reading: 'がくせい · gakusei', pos: '명사', meanings: ['학생'] },
    { word: '友達', kanji: '[友達]', reading: 'ともだち · tomodachi', pos: '명사', meanings: ['친구'] },
    { word: '家族', kanji: '[家族]', reading: 'かぞく · kazoku', pos: '명사', meanings: ['가족'] },
    { word: '時間', kanji: '[時間]', reading: 'じかん · jikan', pos: '명사', meanings: ['시간'] },
    { word: '今日', kanji: '[今日]', reading: 'きょう · kyō', pos: '명사', meanings: ['오늘'] },
    { word: '明日', kanji: '[明日]', reading: 'あした · ashita', pos: '명사', meanings: ['내일'] },
    { word: '昨日', kanji: '[昨日]', reading: 'きのう · kinō', pos: '명사', meanings: ['어제'] },
    { word: '犬', kanji: '[犬]', reading: 'いぬ · inu', pos: '명사', meanings: ['개', '강아지'] },
    { word: '猫', kanji: '[猫]', reading: 'ねこ · neko', pos: '명사', meanings: ['고양이'] },
    { word: '水', kanji: '[水]', reading: 'みず · mizu', pos: '명사', meanings: ['물'] },
    { word: '右', kanji: '[右]', reading: 'みぎ · migi', pos: '명사', meanings: ['오른쪽'] },
    { word: '左', kanji: '[左]', reading: 'ひだり · hidari', pos: '명사', meanings: ['왼쪽'] },
    { word: '上', kanji: '[上]', reading: 'うえ · ue', pos: '명사', meanings: ['위'] },
    { word: '下', kanji: '[下]', reading: 'した · shita', pos: '명사', meanings: ['아래'] },
    { word: '手', kanji: '[手]', reading: 'て · te', pos: '명사', meanings: ['손'] },
    { word: '目', kanji: '[目]', reading: 'め · me', pos: '명사', meanings: ['눈'] },
    { word: '耳', kanji: '[耳]', reading: 'みみ · mimi', pos: '명사', meanings: ['귀'] },
    { word: '口', kanji: '[口]', reading: 'くち · kuchi', pos: '명사', meanings: ['입'] },
    { word: '足', kanji: '[足]', reading: 'あし · ashi', pos: '명사', meanings: ['발', '다리'] },
  ],
  N4: [
    { word: '運動', kanji: '[運動]', reading: 'うんどう · undō', pos: '명사', meanings: ['운동'] },
    { word: '練習', kanji: '[練習]', reading: 'れんしゅう · renshū', pos: '명사', meanings: ['연습'] },
    { word: '説明', kanji: '[説明]', reading: 'せつめい · setsumei', pos: '명사', meanings: ['설명'] },
    { word: '準備', kanji: '[準備]', reading: 'じゅんび · junbi', pos: '명사', meanings: ['준비'] },
    { word: '約束', kanji: '[約束]', reading: 'やくそく · yakusoku', pos: '명사', meanings: ['약속'] },
    { word: '経験', kanji: '[経験]', reading: 'けいけん · keiken', pos: '명사', meanings: ['경험'] },
    { word: '生活', kanji: '[生活]', reading: 'せいかつ · seikatsu', pos: '명사', meanings: ['생활'] },
    { word: '社会', kanji: '[社会]', reading: 'しゃかい · shakai', pos: '명사', meanings: ['사회'] },
    { word: '変える', kanji: '[変える]', reading: 'かえる · kaeru', pos: '동사', meanings: ['바꾸다', '변경하다'] },
    { word: '決める', kanji: '[決める]', reading: 'きめる · kimeru', pos: '동사', meanings: ['결정하다'] },
    { word: '続ける', kanji: '[続ける]', reading: 'つづける · tsuzukeru', pos: '동사', meanings: ['계속하다'] },
    { word: '集める', kanji: '[集める]', reading: 'あつめる · atsumeru', pos: '동사', meanings: ['모으다'] },
    { word: '心配', kanji: '[心配]', reading: 'しんぱい · shinpai', pos: '명사', meanings: ['걱정', '염려'] },
    { word: '丁寧', kanji: '[丁寧]', reading: 'ていねい · teinei', pos: '형용사', meanings: ['정중하다', '꼼꼼하다'] },
    { word: '親切', kanji: '[親切]', reading: 'しんせつ · shinsetsu', pos: '형용사', meanings: ['친절하다'] },
    { word: '特別な', kanji: '[特別な]', reading: 'とくべつな · tokubetsuna', pos: '형용사', meanings: ['특별한'] },
    { word: '自由な', kanji: '[自由な]', reading: 'じゆうな · jiyūna', pos: '형용사', meanings: ['자유로운'] },
    { word: '必要な', kanji: '[必要な]', reading: 'ひつような · hitsuyōna', pos: '형용사', meanings: ['필요한'] },
    { word: '大切な', kanji: '[大切な]', reading: 'たいせつな · taisetsuna', pos: '형용사', meanings: ['소중한'] },
    { word: '考える', kanji: '[考える]', reading: 'かんがえる · kangaeru', pos: '동사', meanings: ['생각하다'] },
    { word: '急ぐ', kanji: '[急ぐ]', reading: 'いそぐ · isogu', pos: '동사', meanings: ['서두르다'] },
    { word: '払う', kanji: '[払う]', reading: 'はらう · harau', pos: '동사', meanings: ['지불하다'] },
    { word: '働く', kanji: '[働く]', reading: 'はたらく · hataraku', pos: '동사', meanings: ['일하다'] },
    { word: '休む', kanji: '[休む]', reading: 'やすむ · yasumu', pos: '동사', meanings: ['쉬다'] },
    { word: '頑張る', kanji: '[頑張る]', reading: 'がんばる · ganbaru', pos: '동사', meanings: ['힘내다', '노력하다'] },
    { word: '探す', kanji: '[探す]', reading: 'さがす · sagasu', pos: '동사', meanings: ['찾다'] },
    { word: '忘れる', kanji: '[忘れる]', reading: 'わすれる · wasureru', pos: '동사', meanings: ['잊다'] },
    { word: '思い出す', kanji: '[思い出す]', reading: 'おもいだす · omoidasu', pos: '동사', meanings: ['생각해내다'] },
    { word: '覚える', kanji: '[覚える]', reading: 'おぼえる · oboeru', pos: '동사', meanings: ['외우다', '기억하다'] },
  ],
  N3: [
    { word: '影響', kanji: '[影響]', reading: 'えいきょう · eikyō', pos: '명사', meanings: ['영향'] },
    { word: '原因', kanji: '[原因]', reading: 'げんいん · gen\'in', pos: '명사', meanings: ['원인'] },
    { word: '結果', kanji: '[結果]', reading: 'けっか · kekka', pos: '명사', meanings: ['결과'] },
    { word: '可能', kanji: '[可能]', reading: 'かのう · kanō', pos: '형용사', meanings: ['가능하다'] },
    { word: '必要', kanji: '[必要]', reading: 'ひつよう · hitsuyō', pos: '형용사', meanings: ['필요하다'] },
    { word: '危険', kanji: '[危険]', reading: 'きけん · kiken', pos: '형용사', meanings: ['위험하다'] },
    { word: '正確', kanji: '[正確]', reading: 'せいかく · seikaku', pos: '형용사', meanings: ['정확하다'] },
    { word: '複雑', kanji: '[複雑]', reading: 'ふくざつ · fukuzatsu', pos: '형용사', meanings: ['복잡하다'] },
    { word: '認める', kanji: '[認める]', reading: 'みとめる · mitomeru', pos: '동사', meanings: ['인정하다', '허가하다'] },
    { word: '断る', kanji: '[断る]', reading: 'ことわる · kotowaru', pos: '동사', meanings: ['거절하다'] },
    { word: '相談', kanji: '[相談]', reading: 'そうだん · sōdan', pos: '명사', meanings: ['상담', '의논'] },
    { word: '目的', kanji: '[目的]', reading: 'もくてき · mokuteki', pos: '명사', meanings: ['목적'] },
    { word: '方法', kanji: '[方法]', reading: 'ほうほう · hōhō', pos: '명사', meanings: ['방법'] },
    { word: '美しい', kanji: '[美しい]', reading: 'うつくしい · utsukushii', pos: '형용사', meanings: ['아름답다', '예쁘다'] },
    { word: '懐かしい', kanji: '[懐かしい]', reading: 'なつかしい · natsukashii', pos: '형용사', meanings: ['그립다', '옛날 생각이 나다'] },
    { word: '深い', kanji: '[深い]', reading: 'ふかい · fukai', pos: '형용사', meanings: ['깊다'] },
    { word: '浅い', kanji: '[浅い]', reading: 'あさい · asai', pos: '형용사', meanings: ['얕다'] },
    { word: '痛い', kanji: '[痛い]', reading: 'いたい · itai', pos: '형용사', meanings: ['아프다'] },
    { word: '辛い', kanji: '[辛い]', reading: 'つらい · tsurai', pos: '형용사', meanings: ['괴롭다', '맵다'] },
    { word: '甘い', kanji: '[甘い]', reading: 'あまい · amai', pos: '형용사', meanings: ['달다', '무르다'] },
    { word: '厳しい', kanji: '[厳しい]', reading: 'きびしい · kibishii', pos: '형용사', meanings: ['엄하다', '혹독하다'] },
    { word: '優しい', kanji: '[優しい]', reading: 'やさしい · yasashii', pos: '형용사', meanings: ['다정하다', '쉽다'] },
    { word: '恐ろしい', kanji: '[恐ろしい]', reading: 'おそろしい · osoroshii', pos: '형용사', meanings: ['무섭다', '끔찍하다'] },
    { word: '素晴らしい', kanji: '[素晴らしい]', reading: 'すばらしい · subarashii', pos: '형용사', meanings: ['훌륭하다', '근사하다'] },
    { word: '珍しい', kanji: '[珍しい]', reading: 'めずらしい · mezurashii', pos: '형용사', meanings: ['드물다', '희귀하다'] },
    { word: '詳しい', kanji: '[詳しい]', reading: 'くわしい · kuwashii', pos: '형용사', meanings: ['상세하다', '자세하다'] },
    { word: '恥ずかしい', kanji: '[恥ずかしい]', reading: 'はずかしい · hazukashii', pos: '형용사', meanings: ['부끄럽다'] },
    { word: '悔しい', kanji: '[悔しい]', reading: 'くやしい · kuyashii', pos: '형용사', meanings: ['분하다', '억울하다'] },
  ],
  N2: [
    { word: '維持', kanji: '[維持]', reading: 'いじ · iji', pos: '명사', meanings: ['유지'] },
    { word: '促進', kanji: '[促進]', reading: 'そくしん · sokushin', pos: '명사', meanings: ['촉진'] },
    { word: '抑制', kanji: '[抑制]', reading: 'よくせい · yokusei', pos: '명사', meanings: ['억제'] },
    { word: '拡大', kanji: '[拡大]', reading: 'かくだい · kakudai', pos: '명사', meanings: ['확대'] },
    { word: '縮小', kanji: '[縮小]', reading: 'しゅくしょう · shukushō', pos: '명사', meanings: ['축소'] },
    { word: '誤解', kanji: '[誤解]', reading: 'ごかい · gokai', pos: '명사', meanings: ['오해'] },
    { word: '矛盾', kanji: '[矛盾]', reading: 'むじゅん · mujun', pos: '명사', meanings: ['모순'] },
    { word: '儚い', kanji: '[儚い]', reading: 'はかない · hakanai', pos: '형용사', meanings: ['덧없다', '무상하다'] },
    { word: '切ない', kanji: '[切ない]', reading: 'せつない · setsunai', pos: '형용사', meanings: ['가슴 아프다', '애틋하다'] },
    { word: '妥当', kanji: '[妥当]', reading: 'だとう · datō', pos: '형용사', meanings: ['타당하다', '적절하다'] },
    { word: '徐々に', kanji: '[徐々に]', reading: 'じょじょに · jojo-ni', pos: '부사', meanings: ['서서히', '점점'] },
    { word: '敢えて', kanji: '[敢えて]', reading: 'あえて · aete', pos: '부사', meanings: ['감히', '굳이'] },
    { word: '抽象的', kanji: '[抽象的]', reading: 'ちゅうしょうてき · chūshōteki', pos: '형용사', meanings: ['추상적'] },
    { word: '具体的', kanji: '[具体的]', reading: 'ぐたいてき · gutaiteki', pos: '형용사', meanings: ['구체적'] },
    { word: '積極的', kanji: '[積極的]', reading: 'せっきょくてき · sekkyokuteki', pos: '형용사', meanings: ['적극적'] },
    { word: '消極的', kanji: '[消極的]', reading: 'しょうきょくてき · shōkyokuteki', pos: '형용사', meanings: ['소극적'] },
    { word: '客観的', kanji: '[客観的]', reading: 'きゃっかんてき · kyakkanteki', pos: '형용사', meanings: ['객관적'] },
    { word: '主観的', kanji: '[主観的]', reading: 'しゅかんてき · shukanteki', pos: '형용사', meanings: ['주관적'] },
    { word: '典型的', kanji: '[典型的]', reading: 'てんけいてき · tenkeiteki', pos: '형용사', meanings: ['전형적'] },
    { word: '効率的', kanji: '[効率的]', reading: 'こうりつてき · kōritsuteki', pos: '형용사', meanings: ['효율적'] },
    { word: '画期的', kanji: '[画期的]', reading: 'かっきてき · kakkiteki', pos: '형용사', meanings: ['획기적'] },
    { word: '致命的', kanji: '[致命的]', reading: 'ちめいてき · chimeiteki', pos: '형용사', meanings: ['치명적'] },
    { word: '圧倒的', kanji: '[圧倒的]', reading: 'あっとうてき · attōteki', pos: '형용사', meanings: ['압도적'] },
    { word: '徹底的', kanji: '[徹底的]', reading: 'てっていてき · tetteiteki', pos: '형용사', meanings: ['철저함'] },
    { word: '相対的', kanji: '[相対的]', reading: 'そうたいてき · sōtaiteki', pos: '형용사', meanings: ['상대적'] },
    { word: '絶対的', kanji: '[絶対的]', reading: 'ぜったいてき · zettaiteki', pos: '형용사', meanings: ['절대적'] },
  ],
  N1: [
    { word: '憂鬱', kanji: '[憂鬱]', reading: 'ゆううつ · yūutsu', pos: '명사', meanings: ['우울', '울적함'] },
    { word: '葛藤', kanji: '[葛藤]', reading: 'かっとう · kattō', pos: '명사', meanings: ['갈등', '충돌'] },
    { word: '逡巡', kanji: '[逡巡]', reading: 'しゅんじゅん · shunjun', pos: '명사', meanings: ['주저', '망설임'] },
    { word: '凛とした', kanji: '[凛とした]', reading: 'りんとした · rin-to shita', pos: '형용사', meanings: ['늠름하다', '단호하다'] },
    { word: '儚げ', kanji: '[儚げ]', reading: 'はかなげ · hakanage', pos: '형용사', meanings: ['덧없어 보이다', '허무하게 보이다'] },
    { word: '鑑みる', kanji: '[鑑みる]', reading: 'かんがみる · kangamiru', pos: '동사', meanings: ['감안하다', '비추어 보다'] },
    { word: '醸し出す', kanji: '[醸し出す]', reading: 'かもしだす · kamoshidasu', pos: '동사', meanings: ['자아내다', '풍기다'] },
    { word: '赴く', kanji: '[赴く]', reading: 'おもむく · omumuku', pos: '동사', meanings: ['향하다', '나아가다'] },
    { word: '漠然と', kanji: '[漠然と]', reading: 'ばくぜんと · bakuzen-to', pos: '부사', meanings: ['막연히', '어렴풋이'] },
    { word: '紛れもなく', kanji: '[紛れもなく]', reading: 'まぎれもなく · magirenaku', pos: '부사', meanings: ['틀림없이', '분명히'] },
    { word: '甚だしい', kanji: '[甚だしい]', reading: 'はなはだしい · hanahadashii', pos: '형용사', meanings: ['극심하다', '대단하다'] },
    { word: '著しい', kanji: '[著しい]', reading: 'いちじるしい · ichijirushii', pos: '형용사', meanings: ['현저하다', '눈부시다'] },
    { word: '煩わしい', kanji: '[煩わしい]', reading: 'わずらわしい · wazurawashii', pos: '형용사', meanings: ['번거롭다', '귀찮다'] },
    { word: '紛らわしい', kanji: '[紛らわしい]', reading: 'まぎらわしい · magirawashii', pos: '형용사', meanings: ['헷갈리기 쉽다'] },
    { word: '華々しい', kanji: '[華々しい]', reading: 'はなばなしい · hanabanashii', pos: '형용사', meanings: ['화려하다', '눈부시다'] },
    { word: '夥しい', kanji: '[夥しい]', reading: 'おびただしい · obitadashii', pos: '형용사', meanings: ['엄청나게 많다'] },
    { word: '空しい', kanji: '[空しい]', reading: 'むなしい · munashii', pos: '형용사', meanings: ['허무하다', '공허하다'] },
    { word: '逞しい', kanji: '[逞しい]', reading: 'たくましい · takumashii', pos: '형용사', meanings: ['늠름하다', '강건하다'] },
    { word: '相応しい', kanji: '[相応しい]', reading: 'ふさわしい · fusawashii', pos: '형용사', meanings: ['어울리다', '걸맞다'] },
    { word: '巧み', kanji: '[巧み]', reading: 'たくみ · takumi', pos: '명사', meanings: ['솜씨가 좋음', '정교함'] },
    { word: '拙い', kanji: '[拙い]', reading: 'つたない · tsutanai', pos: '형용사', meanings: ['서투르다', '졸렬하다'] },
  ],
};
