// 단어 사전 데이터베이스
const wordDB = {
  // ── 猫 ──
  '猫':{'word':'猫','kanji':'ねこ','reading':'ねこ [neko]','meanings':['고양이','온순한 사람 (비유)']},
  '夕焼け':{'word':'夕焼け','kanji':'ゆうやけ','reading':'ゆうやけ [yūyake]','meanings':['저녁노을','노을 빛']},
  '燃えて':{'word':'燃えて','kanji':'もえて','reading':'もえて [moete]','meanings':['타올라 (燃える의 て형)','불타다']},
  '街':{'word':'街','kanji':'まち','reading':'まち [machi]','meanings':['거리, 마을','시가지']},
  '飲み込んで':{'word':'飲み込んで','kanji':'のみこんで','reading':'のみこんで [nomikonde]','meanings':['삼켜서','이해하고']},
  '今日':{'word':'今日','kanji':'きょう','reading':'きょう [kyō]','meanings':['오늘','이 날']},
  '僕':{'word':'僕','kanji':'ぼく','reading':'ぼく [boku]','meanings':['나 (남성 1인칭)','하인 (고어)']},
  '君':{'word':'君','kanji':'きみ','reading':'きみ [kimi]','meanings':['너, 그대 (친근한 2인칭)','임금, 주군 (고어)']},
  '手放して':{'word':'手放して','kanji':'てばなして','reading':'てばなして [tebanashite]','meanings':['손을 떼어, 포기하고','팔아서, 양도하고']},
  '明日':{'word':'明日','kanji':'あした','reading':'あした [ashita]','meanings':['내일','가까운 미래']},
  '不安':{'word':'不安','kanji':'ふあん','reading':'ふあん [fuan]','meanings':['불안, 걱정','불안정한 상태']},
  '嫌':{'word':'嫌','kanji':'いや','reading':'いや [iya]','meanings':['싫다, 꺼리다','불쾌함']},
  '一緒':{'word':'一緒','kanji':'いっしょ','reading':'いっしょ [issho]','meanings':['함께, 같이','동시에']},
  '眠たい':{'word':'眠たい','kanji':'ねむたい','reading':'ねむたい [nemutai]','meanings':['졸리다','무기력하다']},
  '夜':{'word':'夜','kanji':'よる','reading':'よる [yoru]','meanings':['밤','야간']},
  '笑って':{'word':'笑って','kanji':'わらって','reading':'わらって [waratte]','meanings':['웃고, 웃어 (笑う의 て형)','비웃다']},
  '帰ろう':{'word':'帰ろう','kanji':'かえろう','reading':'かえろう [kaerō]','meanings':['돌아가자 (帰る의 의지형)','귀가하자']},
  '昨日':{'word':'昨日','kanji':'きのう','reading':'きのう [kinō]','meanings':['어제','과거']},
  '幻':{'word':'幻','kanji':'まぼろし','reading':'まぼろし [maboroshi]','meanings':['환상, 환영','꿈, 허상']},
  '顔':{'word':'顔','kanji':'かお','reading':'かお [kao]','meanings':['얼굴','표정, 낯']},
  '忘れて':{'word':'忘れて','kanji':'わすれて','reading':'わすれて [wasurete]','meanings':['잊어 (忘れる의 て형)','두고 가다']},
  '馬鹿馬鹿しい':{'word':'馬鹿馬鹿しい','kanji':'ばかばかしい','reading':'ばかばかしい [bakabakashii]','meanings':['어리석다, 우스꽝스럽다','말도 안 된다']},
  '日々':{'word':'日々','kanji':'ひび','reading':'ひび [hibi]','meanings':['나날, 매일매일','하루하루']},
  '気だるさ':{'word':'気だるさ','kanji':'けだるさ','reading':'けだるさ [kedarusa]','meanings':['나른함, 무기력함','피곤한 느낌']},
  '心':{'word':'心','kanji':'こころ','reading':'こころ [kokoro]','meanings':['마음','정신, 감정','의지, 의향']},
  '体':{'word':'体','kanji':'からだ','reading':'からだ [karada]','meanings':['몸, 신체','체질']},
  '喧嘩':{'word':'喧嘩','kanji':'けんか','reading':'けんか [kenka]','meanings':['싸움, 다툼','격투']},
  '頼りない':{'word':'頼りない','kanji':'たよりない','reading':'たよりない [tayorinai]','meanings':['믿음직스럽지 않다','의지가 되지 않다']},
  '寝転んで':{'word':'寝転んで','kanji':'ねころんで','reading':'ねころんで [nekoronde]','meanings':['아무렇게나 드러누워','드러눕다']},
  '現れて':{'word':'現れて','kanji':'あらわれて','reading':'あらわれて [arawarete]','meanings':['나타나','출현해']},
  '何気ない':{'word':'何気ない','kanji':'なにげない','reading':'なにげない [nanigenai]','meanings':['무심한, 아무렇지 않은','자연스러운']},
  '毎日':{'word':'毎日','kanji':'まいにち','reading':'まいにち [mainichi]','meanings':['매일, 매일매일','일상']},
  '染めて':{'word':'染めて','kanji':'そめて','reading':'そめて [somete]','meanings':['물들여, 염색하여','영향 주어']},
  '戻れない':{'word':'戻れない','kanji':'もどれない','reading':'もどれない [modorenai]','meanings':['돌아올 수 없다','되돌릴 수 없다']},
  '声':{'word':'声','kanji':'こえ','reading':'こえ [koe]','meanings':['목소리','소리 (비유)']},
  '側':{'word':'側','kanji':'そば','reading':'そば [soba]','meanings':['옆, 곁','가까운 곳']},
  '走って':{'word':'走って','kanji':'はしって','reading':'はしって [hashitte]','meanings':['달려서 (走る의 て형)','질주하다']},
  '呼んで':{'word':'呼んで','kanji':'よんで','reading':'よんで [yonde]','meanings':['불러서 (呼ぶ의 て형)','부르다']},
  // ── さよならモルテン ──
  '突き止めたい':{'word':'突き止めたい','kanji':'つきとめたい','reading':'つきとめたい [tsukitometai]','meanings':['알아내고 싶다','규명하고 싶다']},
  '叶わない':{'word':'叶わない','kanji':'かなわない','reading':'かなわない [kanawanai]','meanings':['이루어지지 않다','당해낼 수 없다']},
  '借りた':{'word':'借りた','kanji':'かりた','reading':'かりた [karita]','meanings':['빌린','빌다의 과거형']},
  '片手':{'word':'片手','kanji':'かたて','reading':'かたて [katate]','meanings':['한 손','한쪽 손']},
  '川沿い':{'word':'川沿い','kanji':'かわぞい','reading':'かわぞい [kawazoi]','meanings':['강가, 강변','강을 따라']},
  '歩道':{'word':'歩道','kanji':'ほどう','reading':'ほどう [hodō]','meanings':['보도, 인도','사람이 걷는 길']},
  '腕':{'word':'腕','kanji':'うで','reading':'うで [ude]','meanings':['팔','솜씨, 능력']},
  '跳ねた':{'word':'跳ねた','kanji':'はねた','reading':'はねた [haneta]','meanings':['뛰어올랐다','튀어오르다']},
  '転がり':{'word':'転がり','kanji':'ころがり','reading':'ころがり [korogari]','meanings':['구르며, 굴러','넘어지며']},
  '土':{'word':'土','kanji':'つち','reading':'つち [tsuchi]','meanings':['흙, 땅','토양']},
  '匂い':{'word':'匂い','kanji':'におい','reading':'におい [nioi]','meanings':['냄새, 향기','분위기 (비유)']},
  '胸':{'word':'胸','kanji':'むね','reading':'むね [mune]','meanings':['가슴','마음, 감정']},
  '夏':{'word':'夏','kanji':'なつ','reading':'なつ [natsu]','meanings':['여름','활기찬 계절']},
  '背':{'word':'背','kanji':'せ','reading':'せ [se]','meanings':['등, 키','뒤쪽']},
  '悲しみ':{'word':'悲しみ','kanji':'かなしみ','reading':'かなしみ [kanashimi]','meanings':['슬픔','비탄']},
  '資産':{'word':'資産','kanji':'しさん','reading':'しさん [shisan]','meanings':['자산, 재산','소중한 것']},
  '丘':{'word':'丘','kanji':'おか','reading':'おか [oka]','meanings':['언덕','작은 산']},
  '大人':{'word':'大人','kanji':'おとな','reading':'おとな [otona]','meanings':['어른, 성인','성숙한 사람']},
  '離れて':{'word':'離れて','kanji':'はなれて','reading':'はなれて [hanarete]','meanings':['떨어져, 거리가 생겨','헤어져']},
  '懐かしい':{'word':'懐かしい','kanji':'なつかしい','reading':'なつかしい [natsukashii]','meanings':['그립다, 옛날 생각이 나다','추억이 담겨있다']},
  '煌めいて':{'word':'煌めいて','kanji':'きらめいて','reading':'きらめいて [kiramete]','meanings':['반짝이며','빛나며']},
  '愛おしい':{'word':'愛おしい','kanji':'いとおしい','reading':'いとおしい [itōshii]','meanings':['사랑스럽다','소중하다, 애틋하다']},
  '少年':{'word':'少年','kanji':'しょうねん','reading':'しょうねん [shōnen]','meanings':['소년, 어린 남자아이','청소년']},
  '相棒':{'word':'相棒','kanji':'あいぼう','reading':'あいぼう [aibō]','meanings':['단짝, 동반자','파트너']},
  '鳥':{'word':'鳥','kanji':'とり','reading':'とり [tori]','meanings':['새','닭 (비공식)']},
  '旅する':{'word':'旅する','kanji':'たびする','reading':'たびする [tabisuru]','meanings':['여행하다','돌아다니다']},
  '北':{'word':'北','kanji':'きた','reading':'きた [kita]','meanings':['북쪽','북방']},
  // ── カメレオン ──
  '正体':{'word':'正体','kanji':'しょうたい','reading':'しょうたい [shōtai]','meanings':['정체, 본래의 모습','의식, 정신']},
  '迷宮入り':{'word':'迷宮入り','kanji':'めいきゅういり','reading':'めいきゅういり [meikyūiri]','meanings':['미궁에 빠진','해결되지 않은']},
  '難解':{'word':'難解','kanji':'なんかい','reading':'なんかい [nankai]','meanings':['난해하다, 이해하기 어렵다','어려운']},
  'ミステリー':{'word':'ミステリー','kanji':'(외래어)','reading':'ミステリー [misuterii]','meanings':['미스터리, 수수께끼','추리물']},
  '心変わり':{'word':'心変わり','kanji':'こころがわり','reading':'こころがわり [kokorogawari]','meanings':['마음이 변함','변심']},
  '色変わり':{'word':'色変わり','kanji':'いろがわり','reading':'いろがわり [irogawari]','meanings':['색이 변함','색다른 것']},
  '軽やか':{'word':'軽やか','kanji':'かろやか','reading':'かろやか [karoyaka]','meanings':['가볍다, 경쾌하다','산뜻하다']},
  '姿':{'word':'姿','kanji':'すがた','reading':'すがた [sugata]','meanings':['모습, 형태','자태']},
  '悲しい':{'word':'悲しい','kanji':'かなしい','reading':'かなしい [kanashii]','meanings':['슬프다','가슴 아프다']},
  '夕暮れ':{'word':'夕暮れ','kanji':'ゆうぐれ','reading':'ゆうぐれ [yūgure]','meanings':['저녁 무렵, 황혼','해질 녘']},
  '記憶':{'word':'記憶','kanji':'きおく','reading':'きおく [kioku]','meanings':['기억','기억하다']},
  '真実':{'word':'真実','kanji':'しんじつ','reading':'しんじつ [shinjitsu]','meanings':['진실','사실, 진짜']},
  '鮮やか':{'word':'鮮やか','kanji':'あざやか','reading':'あざやか [azayaka]','meanings':['선명하다, 화려하다','훌륭하다']},
  '涙':{'word':'涙','kanji':'なみだ','reading':'なみだ [namida]','meanings':['눈물','슬픔 (비유)']},
  '想い':{'word':'想い','kanji':'おもい','reading':'おもい [omoi]','meanings':['생각, 마음','감정, 그리움']},
  '伝えたい':{'word':'伝えたい','kanji':'つたえたい','reading':'つたえたい [tsutaetai]','meanings':['전하고 싶다','알리고 싶다']},
  '強がり':{'word':'強がり','kanji':'つよがり','reading':'つよがり [tsuyogari]','meanings':['허세 부리기','강한 척']},
  '隣':{'word':'隣','kanji':'となり','reading':'となり [tonari]','meanings':['옆, 이웃','가까운 곳']},
  '変わる':{'word':'変わる','kanji':'かわる','reading':'かわる [kawaru]','meanings':['변하다, 바뀌다','달라지다']},
  '変えた':{'word':'変えた','kanji':'かえた','reading':'かえた [kaeta]','meanings':['바꿨다 (変える의 과거형)','변경했다']},
  '変':{'word':'変','kanji':'へん','reading':'へん [hen]','meanings':['이상하다, 변하다','변화']},
  // ── ヒッチコック ──
  '雨':{'word':'雨','kanji':'あめ','reading':'あめ [ame]','meanings':['비','비가 오다']},
  '報われる':{'word':'報われる','kanji':'むくわれる','reading':'むくわれる [mukuwareru]','meanings':['보상 받다','노력이 인정되다']},
  'さよなら':{'word':'さよなら','kanji':'(히라가나)','reading':'さよなら [sayonara]','meanings':['안녕히 계세요, 작별인사','이별']},
  '先生':{'word':'先生','kanji':'せんせい','reading':'せんせい [sensei]','meanings':['선생님','의사 (경칭)']},
  '人生相談':{'word':'人生相談','kanji':'じんせいそうだん','reading':'じんせいそうだん [jinseisōdan]','meanings':['인생 상담','삶에 관한 조언 구하기']},
  '苦しさ':{'word':'苦しさ','kanji':'くるしさ','reading':'くるしさ [kurushisa]','meanings':['괴로움, 힘듦','고통']},
  '青空':{'word':'青空','kanji':'あおぞら','reading':'あおぞら [aozora]','meanings':['파란 하늘','맑은 하늘']},
  '我儘':{'word':'我儘','kanji':'わがまま','reading':'わがまま [wagamama]','meanings':['제멋대로, 이기적인','응석받이']},
  '青春':{'word':'青春','kanji':'せいしゅん','reading':'せいしゅん [seishun]','meanings':['청춘','젊은 시절']},
  '値札':{'word':'値札','kanji':'ねふだ','reading':'ねふだ [nefuda]','meanings':['가격표','값어치를 매기다 (비유)']},
  '期待':{'word':'期待','kanji':'きたい','reading':'きたい [kitai]','meanings':['기대하다','바라다']},
  '痛い':{'word':'痛い','kanji':'いたい','reading':'いたい [itai]','meanings':['아프다, 고통스럽다','뼈아프다']},
  '穴':{'word':'穴','kanji':'あな','reading':'あな [ana]','meanings':['구멍','결함, 빈자리']},
  '雲':{'word':'雲','kanji':'くも','reading':'くも [kumo]','meanings':['구름','흐린 날씨']},
  '想い出':{'word':'想い出','kanji':'おもいで','reading':'おもいで [omoide]','meanings':['추억','기억에 남는 일']},
  '言葉':{'word':'言葉','kanji':'ことば','reading':'ことば [kotoba]','meanings':['말, 언어','표현']},
  '本当':{'word':'本当','kanji':'ほんとう','reading':'ほんとう [hontō]','meanings':['진짜, 사실','정말로']},
  '感情':{'word':'感情','kanji':'かんじょう','reading':'かんじょう [kanjō]','meanings':['감정','느낌']},
  '世界':{'word':'世界','kanji':'せかい','reading':'せかい [sekai]','meanings':['세계, 세상','분야, 영역']},
  '意味':{'word':'意味','kanji':'いみ','reading':'いみ [imi]','meanings':['의미, 뜻','목적, 이유']},
  // ── 沈丁花 ──
  '沈丁花':{'word':'沈丁花','kanji':'ちんちょうげ','reading':'ちんちょうげ [chinchōge]','meanings':['서향 (식물)','향기로운 봄꽃']},
  'ありがとう':{'word':'ありがとう','kanji':'(히라가나)','reading':'ありがとう [arigatō]','meanings':['감사합니다','고마워']},
  '言えない':{'word':'言えない','kanji':'いえない','reading':'いえない [ienai]','meanings':['말할 수 없다','표현하지 못하다']},
  '負けない':{'word':'負けない','kanji':'まけない','reading':'まけない [makenai]','meanings':['지지 않다','굴하지 않다']},
  '強さ':{'word':'強さ','kanji':'つよさ','reading':'つよさ [tsuyosa]','meanings':['강함, 강도','힘']},
  '教えて':{'word':'教えて','kanji':'おしえて','reading':'おしえて [oshiete]','meanings':['가르쳐줘 (教える의 て형)','알려줘']},
  '種':{'word':'種','kanji':'たね','reading':'たね [tane]','meanings':['씨앗','원인, 이유']},
  '弁当箱':{'word':'弁当箱','kanji':'べんとうばこ','reading':'べんとうばこ [bentōbako]','meanings':['도시락통','도시락']},
  '平凡':{'word':'平凡','kanji':'へいぼん','reading':'へいぼん [heibon]','meanings':['평범하다','특별하지 않다']},
  '母さん':{'word':'母さん','kanji':'かあさん','reading':'かあさん [kāsan]','meanings':['어머니, 엄마','아주머니 (호칭)']},
  '選ぶ':{'word':'選ぶ','kanji':'えらぶ','reading':'えらぶ [erabu]','meanings':['선택하다, 고르다','뽑다']},
  '勇気':{'word':'勇気','kanji':'ゆうき','reading':'ゆうき [yūki]','meanings':['용기','결단력']},
  '花':{'word':'花','kanji':'はな','reading':'はな [hana]','meanings':['꽃','화려함, 최고 (비유)']},
  '旅':{'word':'旅','kanji':'たび','reading':'たび [tabi]','meanings':['여행','인생의 여정 (비유)']},
  '逃げたい':{'word':'逃げたい','kanji':'にげたい','reading':'にげたい [nigetai]','meanings':['도망가고 싶다','피하고 싶다']},
  '諦めて':{'word':'諦めて','kanji':'あきらめて','reading':'あきらめて [akiramete]','meanings':['포기하고 (諦める의 て형)','단념하고']},
  '九月':{'word':'九月','kanji':'くがつ','reading':'くがつ [kugatsu]','meanings':['9월','九月']},
  '友':{'word':'友','kanji':'とも','reading':'とも [tomo]','meanings':['친구','동료']},
  '踏み潰されても':{'word':'踏み潰されても','kanji':'ふみつぶされても','reading':'ふみつぶされても [fumitsubusaretemo]','meanings':['짓밟혀도','부서져도']},
  '起き上がる':{'word':'起き上がる','kanji':'おきあがる','reading':'おきあがる [okiagaru]','meanings':['일어서다, 일어나다','다시 서다']},
  '続く':{'word':'続く','kanji':'つづく','reading':'つづく [tsuzuku]','meanings':['계속되다','이어지다']},
  '香':{'word':'香','kanji':'かお','reading':'かお [kao]','meanings':['향기 (香る 어근)','향내']},
  '巡':{'word':'巡','kanji':'めぐ','reading':'めぐ [megu]','meanings':['돌다 (巡る 어근)','순환하다']},
  '求':{'word':'求','kanji':'もと','reading':'もと [moto]','meanings':['구하다 (求める 어근)','바라다']},
  '聞かせ':{'word':'聞かせ','kanji':'きかせ','reading':'きかせ [kikase]','meanings':['들려주다 (聞かせる 어근)','전달하다']},
  '捨て':{'word':'捨て','kanji':'すて','reading':'すて [sute]','meanings':['버리다 (捨てる 어근)','포기하다']},
  '抱きしめ':{'word':'抱きしめ','kanji':'だきしめ','reading':'だきしめ [dakishime]','meanings':['꼭 안다 (抱きしめる 어근)','포옹']},
  '拭':{'word':'拭','kanji':'ぬぐ','reading':'ぬぐ [nugu]','meanings':['닦다 (拭う 어근)','씻어내다']},
  '開':{'word':'開','kanji':'ひら','reading':'ひら [hira]','meanings':['열다 (開く 어근)','펼치다']},
  '香る':{'word':'香る','kanji':'かおる','reading':'かおる [kaoru]','meanings':['향기가 나다','풍기다']},
  '詰まり':{'word':'詰まり','kanji':'つまり','reading':'つまり [tsumari]','meanings':['막힘 (詰まる 어근)','뭉클함']},
  '汚れ':{'word':'汚れ','kanji':'よごれ','reading':'よごれ [yogore]','meanings':['더러움 (汚れる 어근)','오염']},
  '放':{'word':'放','kanji':'ほう','reading':'ほう [hō]','meanings':['놓다, 내던지다 (放る 어근)','방치']},
  '敵':{'word':'敵','kanji':'かな','reading':'かな [kana]','meanings':['당하다 (敵う 어근)','맞서다']},
  // ── 가사 내 plain string 단어 전체 ──
  '本':{'word':'本','kanji':'ほん','reading':'ほん [hon]','meanings':['책','본, 기본']},
  '持って':{'word':'持って','kanji':'もって','reading':'もって [motte]','meanings':['들고, 가지고 (持つ의 て형)','소지하다']},
  '行く':{'word':'行く','kanji':'いく','reading':'いく [iku]','meanings':['가다','향하다']},
  '乗って':{'word':'乗って','kanji':'のって','reading':'のって [notte]','meanings':['타고 (乗る의 て형)','올라타다']},
  '飛ぶ':{'word':'飛ぶ','kanji':'とぶ','reading':'とぶ [tobu]','meanings':['날다','도약하다']},
  '開く':{'word':'開く','kanji':'ひらく','reading':'ひらく [hiraku]','meanings':['열다, 펼치다','開く']},
  '求める':{'word':'求める','kanji':'もとめる','reading':'もとめる [motomeru]','meanings':['바라다, 원하다','구하다']},
  '来る':{'word':'来る','kanji':'くる','reading':'くる [kuru]','meanings':['오다','찾아오다']},
  '思う':{'word':'思う','kanji':'おもう','reading':'おもう [omou]','meanings':['생각하다','느끼다']},
  '巡る':{'word':'巡る','kanji':'めぐる','reading':'めぐる [meguru]','meanings':['돌다, 순환하다','떠올리다']},
  '聞かせる':{'word':'聞かせる','kanji':'きかせる','reading':'きかせる [kikaseru]','meanings':['들려주다','전하다']},
  '抱きしめる':{'word':'抱きしめる','kanji':'だきしめる','reading':'だきしめる [dakishimeru]','meanings':['꼭 안다','포옹하다']},
  '拭う':{'word':'拭う','kanji':'ぬぐう','reading':'ぬぐう [nuguu]','meanings':['닦다, 씻어내다','지우다']},
  '捨てる':{'word':'捨てる','kanji':'すてる','reading':'すてる [suteru]','meanings':['버리다','포기하다']},
  '詰まる':{'word':'詰まる','kanji':'つまる','reading':'つまる [tsumaru]','meanings':['막히다, 뭉클하다','꽉 차다']},
  '駆ける':{'word':'駆ける','kanji':'かける','reading':'かける [kakeru]','meanings':['달리다, 뛰다','질주하다']},
  '香る':{'word':'香る','kanji':'かおる','reading':'かおる [kaoru]','meanings':['향기가 나다','풍기다']},
  '色':{'word':'色','kanji':'いろ','reading':'いろ [iro]','meanings':['색, 색깔','색조, 빛깔']},
  '道':{'word':'道','kanji':'みち','reading':'みち [michi]','meanings':['길, 도로','방법, 길']},
  '前':{'word':'前','kanji':'まえ','reading':'まえ [mae]','meanings':['앞, 이전','~전, 앞쪽']},
  '中':{'word':'中','kanji':'なか','reading':'なか [naka]','meanings':['안, 가운데','~중, ~동안']},
  '時':{'word':'時','kanji':'とき','reading':'とき [toki]','meanings':['때, 시간','시각, 순간']},
  '実':{'word':'実','kanji':'じつ','reading':'じつ [jitsu]','meanings':['사실, 실제','열매']},
  '無茶苦茶':{'word':'無茶苦茶','kanji':'むちゃくちゃ','reading':'むちゃくちゃ [muchakucha]','meanings':['엉망진창','무리한, 터무니없는']},
  '少し':{'word':'少し','kanji':'すこし','reading':'すこし [sukoshi]','meanings':['조금, 약간','잠시']},
  '高く':{'word':'高く','kanji':'たかく','reading':'たかく [takaku]','meanings':['높게 (高い의 부사형)','비싸게']},
  '幸せ':{'word':'幸せ','kanji':'しあわせ','reading':'しあわせ [shiawase]','meanings':['행복','행운']},
  '悪い':{'word':'悪い','kanji':'わるい','reading':'わるい [warui]','meanings':['나쁘다','악하다']},
  '汚れる':{'word':'汚れる','kanji':'よごれる','reading':'よごれる [yogoreru]','meanings':['더러워지다','오염되다']},
  '放る':{'word':'放る','kanji':'ほうる','reading':'ほうる [hōru]','meanings':['내던지다','방치하다']},
  '塗る':{'word':'塗る','kanji':'ぬる','reading':'ぬる [nuru]','meanings':['칠하다, 바르다','덧칠하다']},
  '色付く':{'word':'色付く','kanji':'いろづく','reading':'いろづく [irozuku]','meanings':['색이 들다, 물들다','익어가다']},
  '敵う':{'word':'敵う','kanji':'かなう','reading':'かなう [kanau]','meanings':['당하다, 맞서다','이길 수 있다']},
  '言う':{'word':'言う','kanji':'いう','reading':'いう [iu]','meanings':['말하다','표현하다']},
  // ── 추가 누락 단어 ──
  '馬鹿':{'word':'馬鹿','kanji':'ばか','reading':'ばか [baka]','meanings':['바보, 멍청이','어리석음']},
  '笑えよ':{'word':'笑えよ','kanji':'わらえよ','reading':'わらえよ [waraevo]','meanings':['웃어라 (笑う 명령형)','비웃어']},
  '傷':{'word':'傷','kanji':'きず','reading':'きず [kizu]','meanings':['상처, 흠','마음의 상처']},
  '何':{'word':'何','kanji':'なに','reading':'なに [nani]','meanings':['무엇, 뭐','어떤']},
  '癖':{'word':'癖','kanji':'くせ','reading':'くせ [kuse]','meanings':['버릇, 습관','~인데도 (역접)']},
  '笑う':{'word':'笑う','kanji':'わらう','reading':'わらう [warau]','meanings':['웃다','비웃다']},
  '笑い':{'word':'笑い','kanji':'わらい','reading':'わらい [warai]','meanings':['웃음','웃는 소리']},
  '人':{'word':'人','kanji':'ひと','reading':'ひと [hito]','meanings':['사람','타인, 남']},
  '笑':{'word':'笑','kanji':'わら','reading':'わら [wara]','meanings':['웃음 (웃다의 어근)','笑う 어근']},
  '楽':{'word':'楽','kanji':'らく','reading':'らく [raku]','meanings':['편안하다, 쉽다','즐거움']},
  '背中':{'word':'背中','kanji':'せなか','reading':'せなか [senaka]','meanings':['등, 등판','뒷모습']},
  '若い':{'word':'若い','kanji':'わかい','reading':'わかい [wakai]','meanings':['젊다, 어리다','미숙하다']},
  '出会う':{'word':'出会う','kanji':'であう','reading':'であう [deau]','meanings':['만나다, 우연히 마주치다','조우하다']},
  '可能':{'word':'可能','kanji':'かのう','reading':'かのう [kanō]','meanings':['가능하다','실현 가능성']},
  '願う':{'word':'願う','kanji':'ねがう','reading':'ねがう [negau]','meanings':['바라다, 원하다','소원하다']},
  '無駄':{'word':'無駄','kanji':'むだ','reading':'むだ [muda]','meanings':['쓸모없다, 헛되다','낭비']},
  '歩く':{'word':'歩く','kanji':'あるく','reading':'あるく [aruku]','meanings':['걷다','나아가다']},
  '息':{'word':'息','kanji':'いき','reading':'いき [iki]','meanings':['숨, 호흡','한숨 (ため息)']},
  '面白い':{'word':'面白い','kanji':'おもしろい','reading':'おもしろい [omoshiroi]','meanings':['재미있다, 흥미롭다','우습다']},
  '全力':{'word':'全力','kanji':'ぜんりょく','reading':'ぜんりょく [zenryoku]','meanings':['전력, 온 힘','전력을 다하다']},
  '全身':{'word':'全身','kanji':'ぜんしん','reading':'ぜんしん [zenshin]','meanings':['온몸, 전신','전체']},
  '矛盾':{'word':'矛盾','kanji':'むじゅん','reading':'むじゅん [mujun]','meanings':['모순','앞뒤가 맞지 않음']},
  '慰める':{'word':'慰める','kanji':'なぐさめる','reading':'なぐさめる [nagusameru]','meanings':['위로하다','달래다']},
  '精一杯':{'word':'精一杯','kanji':'せいいっぱい','reading':'せいいっぱい [seiippai]','meanings':['최선을 다해, 온 힘을 다해','있는 힘껏']},
  '温もり':{'word':'温もり','kanji':'ぬくもり','reading':'ぬくもり [nukumori]','meanings':['온기, 따뜻함','따뜻한 정']},
  '会いたい':{'word':'会いたい','kanji':'あいたい','reading':'あいたい [aitai]','meanings':['만나고 싶다','보고 싶다']},
  '読む':{'word':'読む','kanji':'よむ','reading':'よむ [yomu]','meanings':['읽다','독해하다']},
  '小説':{'word':'小説','kanji':'しょうせつ','reading':'しょうせつ [shōsetsu]','meanings':['소설','이야기']},
  '先':{'word':'先','kanji':'さき','reading':'さき [saki]','meanings':['앞, 미래','먼저, 먼저 하다']},
  '知る':{'word':'知る','kanji':'しる','reading':'しる [shiru]','meanings':['알다','이해하다']},
  '自分':{'word':'自分','kanji':'じぶん','reading':'じぶん [jibun]','meanings':['자신, 자기','나 (1인칭)']},
  '特別':{'word':'特別','kanji':'とくべつ','reading':'とくべつ [tokubetsu]','meanings':['특별하다','각별한']},
  '顔':{'word':'顔','kanji':'かお','reading':'かお [kao]','meanings':['얼굴','표정, 낯']},
  '最後':{'word':'最後','kanji':'さいご','reading':'さいご [saigo]','meanings':['마지막','최후']},
  '急行':{'word':'急行','kanji':'きゅうこう','reading':'きゅうこう [kyūkō]','meanings':['급행','급히 가다']},
  '列車':{'word':'列車','kanji':'れっしゃ','reading':'れっしゃ [ressha]','meanings':['열차, 기차','전동차']},
  '幸せ':{'word':'幸せ','kanji':'しあわせ','reading':'しあわせ [shiawase]','meanings':['행복, 행운','기쁨']},
  '何度':{'word':'何度','kanji':'なんど','reading':'なんど [nando]','meanings':['몇 번, 여러 번','몇 도']},
  '現実':{'word':'現実','kanji':'げんじつ','reading':'げんじつ [genjitsu]','meanings':['현실','실제 상황']},
  '死ぬ':{'word':'死ぬ','kanji':'しぬ','reading':'しぬ [shinu]','meanings':['죽다','사망하다']},
  '風':{'word':'風','kanji':'かぜ','reading':'かぜ [kaze]','meanings':['바람','풍조, 경향']},
  '夢':{'word':'夢','kanji':'ゆめ','reading':'ゆめ [yume]','meanings':['꿈','이상, 희망']},
  '今日':{'word':'今日','kanji':'きょう','reading':'きょう [kyō]','meanings':['오늘','이 날']},
  '進む':{'word':'進む','kanji':'すすむ','reading':'すすむ [susumu]','meanings':['나아가다, 전진하다','진행되다']},
  '若':{'word':'若','kanji':'わか','reading':'わか [waka]','meanings':['젊다, 어리다 (若い 어근)','미숙함']},
  '出会':{'word':'出会','kanji':'であ','reading':'であ [dea]','meanings':['만남 (出会う 어근)','우연한 만남']},
  '願':{'word':'願','kanji':'ねが','reading':'ねが [nega]','meanings':['소원, 바람 (願う 어근)','부탁']},
  '歩':{'word':'歩','kanji':'ある','reading':'ある [aru]','meanings':['걷다 (歩く 어근)','걸음']},
  '面白':{'word':'面白','kanji':'おもしろ','reading':'おもしろ [omoshiro]','meanings':['재미있다 (面白い 어근)','흥미롭다']},
  '忘れ':{'word':'忘れ','kanji':'わすれ','reading':'わすれ [wasure]','meanings':['잊다 (忘れる 어근)','망각']},
  '慰':{'word':'慰','kanji':'なぐさ','reading':'なぐさ [nagusa]','meanings':['위로하다 (慰める 어근)','달래다']},
  '温':{'word':'温','kanji':'ぬく','reading':'ぬく [nuku]','meanings':['따뜻함 (温もり 어근)','온기']},
  '会':{'word':'会','kanji':'あ','reading':'あ [a]','meanings':['만나다 (会う 어근)','조우']},
  '忘':{'word':'忘','kanji':'わす','reading':'わす [wasu]','meanings':['잊다 (忘れる 어근)','기억을 잃다']},
  '読':{'word':'読','kanji':'よ','reading':'よ [yo]','meanings':['읽다 (読む 어근)','독서']},
  '終':{'word':'終','kanji':'お','reading':'お [o]','meanings':['끝내다 (終わる 어근)','마치다']},
  '知':{'word':'知','kanji':'し','reading':'し [shi]','meanings':['알다 (知る 어근)','지식']},
  '伸':{'word':'伸','kanji':'の','reading':'の [no]','meanings':['늘어나다 (伸びる 어근)','성장하다']},
  '追':{'word':'追','kanji':'お','reading':'お [o]','meanings':['쫓다 (追う 어근)','추적하다']},
  '空':{'word':'空','kanji':'そら','reading':'そら [sora]','meanings':['하늘','비다, 텅 빔']},
  '飛':{'word':'飛','kanji':'と','reading':'と [to]','meanings':['날다 (飛ぶ 어근)','비행']},
  '遠':{'word':'遠','kanji':'とお','reading':'とお [tō]','meanings':['멀다 (遠い 어근)','거리가 있다']},
  '別':{'word':'別','kanji':'わか','reading':'わか [waka]','meanings':['헤어지다 (別れる 어근)','이별']},
  '誰':{'word':'誰','kanji':'だれ','reading':'だれ [dare]','meanings':['누구','어떤 사람']},
  '目':{'word':'目','kanji':'め','reading':'め [me]','meanings':['눈 (신체)','시선, 눈길']},
  '今':{'word':'今','kanji':'いま','reading':'いま [ima]','meanings':['지금, 현재','이 순간']},
  '生':{'word':'生','kanji':'い','reading':'い [i]','meanings':['살다 (生きる 어근)','삶']},
  '死':{'word':'死','kanji':'しぬ','reading':'しぬ [shinu]','meanings':['죽다','사망하다']},
  '暗':{'word':'暗','kanji':'くら','reading':'くら [kura]','meanings':['어둡다 (暗い 어근)','암울하다']},
  '進':{'word':'進','kanji':'すす','reading':'すす [susu]','meanings':['나아가다 (進む 어근)','전진']},
  '思':{'word':'思','kanji':'おも','reading':'おも [omo]','meanings':['생각하다 (思う 어근)','느끼다']},
  '振り返る':{'word':'振り返る','kanji':'ふりかえる','reading':'ふりかえる [furikaeru]','meanings':['돌아보다','되돌아보다']},
  '思う':{'word':'思う','kanji':'おもう','reading':'おもう [omou]','meanings':['생각하다','느끼다']},
  // ── ヒッチコック 추가 단어 ──
  '近づく':{'word':'近づく','kanji':'ちかづく','reading':'ちかづく [chikazuku]','meanings':['가까워지다, 다가가다','접근하다']},
  '騒めく':{'word':'騒めく','kanji':'ざわめく','reading':'ざわめく [zawameku]','meanings':['술렁이다, 웅성거리다','소란스럽다']},
  '笑われ':{'word':'笑われ','kanji':'わらわれ','reading':'わらわれ [waraware]','meanings':['비웃음을 당하다 (笑う 수동형 어근)','놀림받다']},
  '報われる':{'word':'報われる','kanji':'むくわれる','reading':'むくわれる [mukuwareru]','meanings':['보상받다','노력이 인정되다']},
  '裂いて':{'word':'裂いて','kanji':'さいて','reading':'さいて [saite]','meanings':['찢어 (裂く의 て형)','갈라놓다']},
  '数瞬':{'word':'数瞬','kanji':'すうしゅん','reading':'すうしゅん [sūshun]','meanings':['찰나, 짧은 순간','몇 순간']},
  '足':{'word':'足','kanji':'あし','reading':'あし [ashi]','meanings':['발, 다리','걸음']},
  '止まって':{'word':'止まって','kanji':'とまって','reading':'とまって [tomatte]','meanings':['멈춰서 (止まる의 て형)','정지하다']},
  '生きて':{'word':'生きて','kanji':'いきて','reading':'いきて [ikite]','meanings':['살아서 (生きる의 て형)','생존하다']},
  '嘘':{'word':'嘘','kanji':'うそ','reading':'うそ [uso]','meanings':['거짓말','허위']},
  'つける':{'word':'つける','kanji':'(히라가나)','reading':'つける [tsukeru]','meanings':['붙이다, 달다','~할 수 있다 (가능 접속)']},
  '得':{'word':'得','kanji':'とく','reading':'とく [toku]','meanings':['이익, 이득','유리하다']},
  '文字':{'word':'文字','kanji':'もじ','reading':'もじ [moji]','meanings':['문자, 글자','글씨']},
  '辛さ':{'word':'辛さ','kanji':'つらさ','reading':'つらさ [tsurasa]','meanings':['괴로움, 힘듦','신맛']},
  '線':{'word':'線','kanji':'せん','reading':'せん [sen]','meanings':['선, 줄','라인']},
  '値札':{'word':'値札','kanji':'ねふだ','reading':'ねふだ [nefuda]','meanings':['가격표','값어치를 매기다 (비유)']},
  '貼られ':{'word':'貼られ','kanji':'はられ','reading':'はられ [harare]','meanings':['붙여져 (貼る의 수동형 어근)','부착되다']},
  '指':{'word':'指','kanji':'ゆび','reading':'ゆび [yubi]','meanings':['손가락','가리키다']},
  '描こう':{'word':'描こう','kanji':'えがこう','reading':'えがこう [egakō]','meanings':['그리자 (描く의 의지형)','그려보자']},
  '散際':{'word':'散際','kanji':'ちりぎわ','reading':'ちりぎわ [chirigiwa]','meanings':['흩어지는 순간, 지는 순간','최후의 순간']},
  '値が付く':{'word':'値が付く','kanji':'ねがつく','reading':'ねがつく [negatsuku]','meanings':['값이 매겨지다','가격이 붙다']},
  '忘れちゃう':{'word':'忘れちゃう','kanji':'わすれちゃう','reading':'わすれちゃう [wasurechau]','meanings':['잊어버리다 (忘れてしまう의 구어형)','까먹다']},
  '詭弁':{'word':'詭弁','kanji':'きべん','reading':'きべん [kiben]','meanings':['궤변, 말장난','억지 논리']},
  '瞑って':{'word':'瞑って','kanji':'つむって','reading':'つむって [tsumutte]','meanings':['감아 (瞑る의 て형)','눈을 감다']},
  '瞑り':{'word':'瞑り','kanji':'つむり','reading':'つむり [tsumuri]','meanings':['감기 (瞑る의 연용형)','눈을 감는 것']},
  '吹かれ':{'word':'吹かれ','kanji':'ふかれ','reading':'ふかれ [fukare]','meanings':['바람에 맞다 (吹く의 수동형 어근)','바람을 쐬다']},
  '痛んで':{'word':'痛んで','kanji':'いたんで','reading':'いたんで [itande]','meanings':['아파서 (痛む의 て형)','상하다']},
  '人生':{'word':'人生','kanji':'じんせい','reading':'じんせい [jinsei]','meanings':['인생, 삶','생애']},
  '相談':{'word':'相談','kanji':'そうだん','reading':'そうだん [sōdan]','meanings':['상담, 상의','의논']},
  '通り過ぎ':{'word':'通り過ぎ','kanji':'とおりすぎ','reading':'とおりすぎ [tōrisugi]','meanings':['지나쳐가다 (通り過ぎる 어근)','빠르게 지나가다']},
  // ── Missing Kanji from Lyrics ──
  '家':{'word':'家','kanji':'いえ','reading':'いえ [ie]','meanings':['집','가정']},
  '起':{'word':'起','kanji':'お','reading':'お [o]','meanings':['일어나다 (起きる 어근)','기상']},
  '来':{'word':'来','kanji':'く','reading':'く [ku]','meanings':['오다 (来る 어근)','내방']},
  '丈':{'word':'丈','kanji':'たけ','reading':'たけ [take]','meanings':['키, 길이','(背丈 - 키)']},
  '一':{'word':'一','kanji':'いち','reading':'いち [ichi]','meanings':['하나','일']},
  '枝':{'word':'枝','kanji':'えだ','reading':'えだ [eda]','meanings':['나뭇가지','가지']},
  '褪':{'word':'褪','kanji':'あせ','reading':'あせ [ase]','meanings':['바래다 (褪せる 어근)','퇴색']},
  '数':{'word':'数','kanji':'すう','reading':'すう [sū]','meanings':['수, 여러','몇 (数-)']},
  '百':{'word':'百','kanji':'ひゃく','reading':'ひゃく [hyaku]','meanings':['백, 백 개','많은']},
  '頃':{'word':'頃','kanji':'ころ','reading':'ころ [koro]','meanings':['무렵, 즈음','시기']},
  '気':{'word':'気','kanji':'き','reading':'き [ki]','meanings':['기분, 마음','기운']},
  '見':{'word':'見','kanji':'み','reading':'み [mi]','meanings':['보다 (見る 어근)','보이다']},
  '紙':{'word':'紙','kanji':'かみ','reading':'かみ [kami]','meanings':['종이','지면']},
  '捲':{'word':'捲','kanji':'めく','reading':'めく [meku]','meanings':['넘기다 (捲る 어근)','들추다']},
  '寂':{'word':'寂','kanji':'さび','reading':'さび [sabi]','meanings':['쓸쓸하다 (寂れる 어근)','적막']},
  '駅':{'word':'駅','kanji':'えき','reading':'えき [eki]','meanings':['역','정거장']},
  '隙':{'word':'隙','kanji':'すき','reading':'すき [suki]','meanings':['틈, 빈틈','여가']},
  '間':{'word':'間','kanji':'ま','reading':'ま [ma]','meanings':['사이, 간격','방']},
  '吹':{'word':'吹','kanji':'ふ','reading':'ふ [fu]','meanings':['불다 (吹く 어근)','입김']},
  '抜':{'word':'抜','kanji':'ぬ','reading':'ぬ [nu]','meanings':['빠지다 (抜ける 어근)','뽑다']},
  '当':{'word':'当','kanji':'あ','reading':'あ [a]','meanings':['맞다 (当たる 어근)','당장']},
  '経':{'word':'経','kanji':'へ','reading':'へ [he]','meanings':['지나다 (経る 어근)','경과']},
  '通':{'word':'通','kanji':'つう','reading':'つう [tsū]','meanings':['통하다 (通じる 어근)','다니다']},
  '話':{'word':'話','kanji':'わ','reading':'わ [wa]','meanings':['이야기 (話 어근)','대화']},
  '画':{'word':'画','kanji':'が','reading':'が [ga]','meanings':['그림, 화면','획수']},
  '面':{'word':'面','kanji':'めん','reading':'めん [men]','meanings':['면, 화면','얼굴']},
  '映':{'word':'映','kanji':'うつ','reading':'うつ [utsu]','meanings':['비치다 (映る 어근)','상영']},
  '塗':{'word':'塗','kanji':'ぬ','reading':'ぬ [nu]','meanings':['칠하다 (塗る 어근)','바르다']},
  '上':{'word':'上','kanji':'うえ','reading':'うえ [ue]','meanings':['위, 상단','표면']},
  '白':{'word':'白','kanji':'しろ','reading':'しろ [shiro]','meanings':['하얗다 (白い 어근)','흰색']},
  '絵':{'word':'絵','kanji':'え','reading':'え [e]','meanings':['그림','회화']},
  '具':{'word':'具','kanji':'ぐ','reading':'ぐ [gu]','meanings':['도구 (絵の具 등)','갖추다']},
  '全':{'word':'全','kanji':'ぜん','reading':'ぜん [zen]','meanings':['전부, 모든','전체']},
  '台':{'word':'台','kanji':'だい','reading':'だい [dai]','meanings':['대, 받침 (台無し 어근)','대수']},
  '無':{'word':'無','kanji':'な','reading':'な [na]','meanings':['없다 (無い 어근)','무']},
  '出':{'word':'出','kanji':'で','reading':'で [de]','meanings':['나가다 (出る 어근)','출발']},
  '滲':{'word':'滲','kanji':'にじ','reading':'にじ [niji]','meanings':['번지다 (滲む 어근)','스며들다']},
  '似':{'word':'似','kanji':'に','reading':'に [ni]','meanings':['어울리다 (似合う 어근)','닮다']},
  '合':{'word':'合','kanji':'あ','reading':'あ [a]','meanings':['맞다 (合う 어근)','합치다']},
  '構':{'word':'構','kanji':'かま','reading':'かま [kama]','meanings':['상관하다 (構う 어근)','신경쓰다']},
  '口':{'word':'口','kanji':'くち','reading':'くち [kuchi]','meanings':['입','말']},
  '単':{'word':'単','kanji':'たん','reading':'たん [tan]','meanings':['단 (単純 등)','단일']},
  '純':{'word':'純','kanji':'じゅん','reading':'じゅん [jun]','meanings':['순수 (単純 등)','순진']},
  '居':{'word':'居','kanji':'い','reading':'い [i]','meanings':['있다 (居る 어근)','존재']},
  '懐':{'word':'懐','kanji':'なつ','reading':'なつ [natsu]','meanings':['그립다 (懐かしい 어근)','품']},
  '裂':{'word':'裂','kanji':'さ','reading':'さ [sa]','meanings':['찢다 (裂く 어근)','분열']},
  '言':{'word':'言','kanji':'い','reading':'い [i]','meanings':['말하다 (言う 어근)','언어']},
  '欲':{'word':'欲','kanji':'ほ','reading':'ほ [ho]','meanings':['원하다 (欲しい 어근)','욕망']},
  '含':{'word':'含','kanji':'ふく','reading':'ふく [fuku]','meanings':['포함하다 (含む 어근)','가득 담다']},
  '埋':{'word':'埋','kanji':'う','reading':'う [u]','meanings':['메우다 (埋める 어근)','묻다']},
  '方':{'word':'方','kanji':'かた','reading':'かた [kata]','meanings':['방법 (やり方 등)','쪽, 방향']},
  '書':{'word':'書','kanji':'か','reading':'か [ka]','meanings':['쓰다 (書く 어근)','서적']},
  '高':{'word':'高','kanji':'たか','reading':'たか [taka]','meanings':['높다 (高い 어근)','비싸다']},
  '売':{'word':'売','kanji':'う','reading':'う [u]','meanings':['팔다 (売れる 어근)','판매']},
  '強':{'word':'強','kanji':'つよ','reading':'つよ [tsuyo]','meanings':['강하다 (強い 어근)','힘']},
  '部':{'word':'部','kanji':'ぶ','reading':'ぶ [bu]','meanings':['부 (部分 등)','조직']},
  '分':{'word':'分','kanji':'ぶん','reading':'ぶん [bun]','meanings':['분 (部分 등)','나누다']},
  '十':{'word':'十','kanji':'じゅう','reading':'じゅう [jū]','meanings':['십','10']},
  '月':{'word':'月','kanji':'がつ','reading':'がつ [gatsu]','meanings':['월','달']},
  '愛':{'word':'愛','kanji':'あい','reading':'あい [ai]','meanings':['사랑','애정']},
  '食':{'word':'食','kanji':'た','reading':'た [ta]','meanings':['먹다 (食べる 어근)','음식']},
  '切':{'word':'切','kanji':'き','reading':'き [ki]','meanings':['자르다 (切る 어근)','끊다']},
  '残':{'word':'残','kanji':'のこ','reading':'のこ [noko]','meanings':['남기다 (残す 어근)','잔여']},
  '二':{'word':'二','kanji':'に','reading':'に [ni]','meanings':['이, 둘','2']},
  '選':{'word':'選','kanji':'えら','reading':'えら [era]','meanings':['고르다 (選ぶ 어근)','선택']},
  '丁':{'word':'丁','kanji':'ちょう','reading':'ちょう [chō]','meanings':['정 (一丁前 등)','구역']},
  '共':{'word':'共','kanji':'とも','reading':'とも [tomo]','meanings':['함께 (共に)','공동']},
  '迎':{'word':'迎','kanji':'むか','reading':'むか [muka]','meanings':['맞이하다 (迎える 어근)','환영']},
  '日':{'word':'日','kanji':'ひ','reading':'ひ [hi]','meanings':['날, 일','하루']},
};

// SONGS — segments: [kanji, furigana] or plain string
